Marketing budget proposal
StarterSquad/circle-decisions pull request #3
Opened 2022-09-08 13:26 UTC by iwein

Adds proposal for marketing budget. Should be merged after #1 by Tiziano

2022-09-22 09:41 UTC, TizianoPerrucci requested changes

2022-09-22 09:41 UTC, TizianoPerrucci commented on proposals/1.marketing-budget.md
> +- budget: €50k / year
@dmitryevseev can you confirm this budget is reasonable according to Squads book ?

2022-09-22 09:41 UTC, TizianoPerrucci commented on proposals/1.marketing-budget.md
> +- maintainer: tbd
in order for the proposal to be accepted this must be defined

2022-09-26 14:57 UTC, dmitryevseev commented on proposals/1.marketing-budget.md
> +- budget: €50k / year
@TizianoPerrucci I'd phrase it as up to 50k/year. We discussed it with Iwein and came to the same understanding of how this money could be spent – they won't be allocated as a large payment, but some portion will be paid to find a working scenario (validation). After that working scenario is scaled. And it will be repeated on and on.

2022-09-27 14:14 UTC, iwein commented on proposals/1.marketing-budget.md
> +- budget: €50k / year
Delegated to Martin Braak (our accountant, see mail @TizianoPerrucci @dmitryevseev ). He's more knowledgable on this than any of us imo.

2022-10-06 09:34 UTC, TizianoPerrucci approved these changes

2022-10-06 09:41 UTC, iwein reviewed
All objections resolved in today's meeting

2022-10-06 09:41 UTC, merged